name: automerge

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NPM_CONFIG_LOGLEVEL: error
  NPM_CONFIG_JOBS: max
  NPM_CONFIG_PROGRESS: false
  # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  automerge:
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
    - run: npm ci
    - run: ./src/bin.js
